name: Build LaTeX document
on: [ push, pull_request ]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: dante-ev/latex-action@latest
        with:
          args: -lualatex --output-directory=out
          root_file: Bewerbung.tex
      - name: Add, Commit & Push
        uses: EndBug/add-and-commit@latest # You can change this to use a specific version
        with:
          add: 'out/Bewerbung.pdf'
          default_author: github_actor
          message: 'Commit from GitHub Actions workflow.'
          signoff: true